#!/bin/bash

# Echo all statements
set -x

# Basic Setup
RM="sudo rm -fR"

# Uninstall homebrew
echo "y" | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"

# Clean Home Directory
$RM ~/.DS_Store
$RM ~/.Trash
$RM ~/.bash_history
$RM ~/.config
$RM ~/.emacs.d
$RM ~/.ssh/known_hosts
$RM ~/Desktop/*
$RM ~/Documents/*
$RM ~/Downloads/*
$RM ~/Library/Application\ Support
$RM ~/Library/Caches/*
$RM ~/Library/Containers/com.docker.docker
$RM ~/Library/Containers/com.tinyspeck.slackmacgap
$RM ~/Library/Developer
$RM ~/Library/Logs/*
$RM ~/Movies
$RM ~/Music

# Clean machine
$RM /var/log/*
$RM /Library/Developer/CommandLineTools
sudo find / -type f -name .DS_Store -delete &> /dev/null &

# Reset shell
chsh -s /bin/bash
