#!/bin/bash

DEVELOPMENT_PATH=$HOME/src
FILESYSTEM_MIRROR=./filesystem
USER_SHELL=/usr/local/bin/bash

# Create expected directorys
mkdir -p $DEVELOPMENT_PATH

# Homebrew
echo | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor

# XCode Command Line Tools
xcode-select --install

# Create SSH Keys
scripts/ssh-keys

# Symlinks
scripts/symlinks

# Homebrew
scripts/homebrew

# Set shell
sudo install -o root -g wheel -m 0644 $FILESYSTEM_MIRROR/etc/shells /etc
chsh -s $USER_SHELL
